# Generated by Django 4.0.3 on 2022-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('complaint', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
