# Generated by Django 4.0.3 on 2022-03-14 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0002_complaint_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
