# Generated by Django 4.0.3 on 2022-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0003_remove_complaint_name_complaint_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField()),
                ('metin', models.TextField()),
                ('tarih', models.DateField()),
                ('kullanici', models.TextField()),
                ('nitelikler', models.TextField()),
            ],
        ),
    ]
